---

image: python:3.8-buster

stages:
  - test
tests:
  stage: test
  tags:
    - has-generic
    - docker
  script:
    - pip install -U poetry
    - make provision-environment
    - make lint
    - make coverage
